### ISSUE TITLE
Fix test_api.cpp's test_Boolean failures

### ISSUE THREAD

**Issue by sdwilsh** [zpao/v8monkey#10]
TEST-UNEXPECTED-FAIL | c:/Code/v8monkey/js/src/v8api/test/test_api.cpp | Expected true, got false at line 288
TEST-UNEXPECTED-FAIL | c:/Code/v8monkey/js/src/v8api/test/test_api.cpp | Expected true, got false at line 290

They fail on buildbot in opt builds and all windows builds.  I can't get visual studio (express edition) to break for me given source code, and my normal trick (http://msdn.microsoft.com/en-us/library/a329t4ed%28VS.71%29.aspx) doesn't seem to work either.

**Comment by robarnold** [comment]
Fix v8::Undefined() and v8::Null(). Closed by 10b63f65b33131844c2daed184e7086fe484fac5. Closed by 10b63f65b33131844c2daed184e7086fe484fac5.
