### ISSUE TITLE
Fix test_api.cpp's test_Handles failures

### ISSUE THREAD

**Issue by sdwilsh** [zpao/v8monkey#11]
The test is currently disabled.  Failure is:
TEST-UNEXPECTED-FAIL | c:/Code/v8monkey/js/src/v8api/test/test_api.cpp | Expected true, got false at line 159

**Comment by robarnold** [comment]
This passes for me and I don't think we changed any of the handle code. On what platforms does this fail?

**Comment by sdwilsh** [comment]
On windows debug, I get:
`TEST-UNEXPECTED-FAIL | c:/Code/v8monkey/js/src/v8api/test/test_api.cpp | Expected true, got false at line 180`

**Comment by zpao** [comment]
This is passing for me (OSX / debug). Want to try re-enabling it locally and see if it's still failing?

**Comment by sdwilsh** [comment]
It was two days ago.  I'd be surprised if something has changed since that code has not.

**Comment by robarnold** [comment]
Fix v8::Undefined() and v8::Null(). Closed by 10b63f65b33131844c2daed184e7086fe484fac5. Closed by 10b63f65b33131844c2daed184e7086fe484fac5.
