### ISSUE TITLE
Fix test_string.cpp's test_WriteUtf8 failures

### ISSUE THREAD

**Issue by sdwilsh** [zpao/v8monkey#15]
Really busted right now.  Fixing this might also fix Issue 14.

**Comment by zpao** [comment]
Enable test_WriteUtf8 and test_Utf8Value_length. Closed by 8c6bdff04171952affeaacac3bbaa5f5f0332e2d. Closed by 8c6bdff04171952affeaacac3bbaa5f5f0332e2d.
