### ISSUE TITLE
v8-debug.h not in v8monkey

### ISSUE THREAD

**Issue by jhford** [zpao/v8monkey#39]
Looks like spidernode wants v8-debug.h.  We don't have it.

<pre>
[52/74] cxx: src/node.cc -> build/default/src/node_3.o
/usr/bin/g++ -pthread -arch x86_64 -g -O3 -DHAVE_OPENSSL=1 -DHAVE_MONOTONIC_CLOCK=0 -DEV_FORK_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_MULTIPLICITY=0 -DX_STACKSIZE=65536 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DEV_MULTIPLICITY=0 -DHAVE_FDATASYNC=0 -DPLATFORM="darwin" -D__POSIX__=1 -Wno-unused-parameter -D_FORTIFY_SOURCE=2 -DNDEBUG -Idefault/src -I../src -Idefault/deps/libeio -I../deps/libeio -Idefault/deps/http_parser -I../deps/http_parser -Idefault/deps/libev -I../deps/libev -Idefault/deps/c-ares -I../deps/c-ares -Idefault/deps/c-ares/darwin-x64 -I../deps/c-ares/darwin-x64 -I/Users/jhford/node/include/js ../src/node.cc -c -o default/src/node_3.o
../src/node.cc:24:22: error: v8-debug.h: No such file or directory
In file included from ../src/node.cc:70:
../src/node_string.h:35: error: expected class-name before ‘{’ token
../src/node.cc: In function ‘void node::Tick()’:
../src/node.cc:233: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc: In function ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’:
../src/node.cc:1027: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1035: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1037: error: ‘Concat’ is not a member of ‘v8::String’
../src/node.cc:1037: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1038: error: ‘Concat’ is not a member of ‘v8::String’
.....
</pre>

**Comment by jhford** [comment]
Looking at 
"--debug               Build debug variant [Default: False]"
it looks like we aren't building debug of spidernode.

**Comment by sdwilsh** [comment]
This is their equivalent to jsd it looks like.  Fun times!

**Comment by sdwilsh** [comment]
I think I have this locally, I just need Issue #40 fixed so I can test it properly.
