### ISSUE TITLE
Fix test_api.cpp's test_CheckForCrossContextObjectLiterals failures

### ISSUE THREAD

**Issue by zpao** [zpao/v8monkey#46]
This calls `V8::Initialize()` so I'm guessing is expecting new contexts to work. But we assert and segfault instead.

**Comment by sdwilsh** [comment]
The problem here is that we end up calling `JS_NewRuntime` twice.  Once for everything we do earlier, and then once for this test.  When we call `JS_SetCStringsAreUTF8` in `V8::Initialize`, it asserts that we've already called `JS_NewRuntime`.
