### ISSUE TITLE
cxx: src/node.cc -> build/default/src/node_3.o : ../src/node_string.h:35: error: expected class-name before ‘{’ token

### ISSUE THREAD

**Issue by jhford** [zpao/v8monkey#48]
I am currently running the node configure and make, using

<pre>./configure \
    --shared-v8 \
    --shared-v8-libname=mozjs \
    --shared-v8-includes=/Users/jhford/node/include/js \
    --shared-v8-libpath=/Users/jhford/node/lib

make</pre>

Because I am not getting past compiling, i don't know if libname and libpath are correct.  My v8monkey was built using a slightly modified buildbot build.sh script 

<pre>
[52/74] cxx: src/node.cc -> build/default/src/node_3.o
/usr/bin/g++ -pthread -arch x86_64 -g -O3 -DHAVE_OPENSSL=1 -DHAVE_MONOTONIC_CLOCK=0 -DEV_FORK_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_MULTIPLICITY=0 -DX_STACKSIZE=65536 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DEV_MULTIPLICITY=0 -DHAVE_FDATASYNC=0 -DPLATFORM="darwin" -D__POSIX__=1 -Wno-unused-parameter -D_FORTIFY_SOURCE=2 -DNDEBUG -Idefault/src -I../src -Idefault/deps/libeio -I../deps/libeio -Idefault/deps/http_parser -I../deps/http_parser -Idefault/deps/libev -I../deps/libev -Idefault/deps/c-ares -I../deps/c-ares -Idefault/deps/c-ares/darwin-x64 -I../deps/c-ares/darwin-x64 -I/Users/jhford/node/include/js ../src/node.cc -c -o default/src/node_3.o
In file included from ../src/node.cc:70:
../src/node_string.h:35: error: expected class-name before ‘{’ token
../src/node.cc: In function ‘void node::Tick()’:
../src/node.cc:233: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc: In function ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’:
../src/node.cc:1027: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1035: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1037: error: ‘Concat’ is not a member of ‘v8::String’
../src/node.cc:1037: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1038: error: ‘Concat’ is not a member of ‘v8::String’
../src/node.cc:1041: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1042: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1043: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1044: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1048: error: ‘Concat’ is not a member of ‘v8::String’
../src/node.cc:1048: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1049: error: ‘Concat’ is not a member of ‘v8::String’
../src/node.cc:1050: error: ‘Concat’ is not a member of ‘v8::String’
../src/node.cc:1050: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1061: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc: In function ‘v8::Handle<v8::Value> node::FromConstructorTemplate(v8::Persistent<v8::FunctionTemplate>&, const v8::Arguments&)’:
../src/node.cc:1081: error: ‘struct v8::HandleScope’ has no member named ‘Close’
../src/node.cc: In function ‘v8::Local<v8::Value> node::Encode(const void*, size_t, node::encoding)’:
../src/node.cc:1124: error: ‘struct v8::HandleScope’ has no member named ‘Close’
../src/node.cc:1124: error: ‘Empty’ is not a member of ‘v8::String’
../src/node.cc:1133: error: no matching function for call to ‘v8::String::New(uint16_t*&, size_t&)’
/Users/jhford/node/include/js/v8.h:592: note: candidates are: static v8::Local<v8::String> v8::String::New(const char*, int)
../src/node.cc:1135: error: ‘struct v8::HandleScope’ has no member named ‘Close’
../src/node.cc:1140: error: ‘struct v8::HandleScope’ has no member named ‘Close’
../src/node.cc: In function ‘v8::Local<v8::Value> node::ExecuteString(v8::Handle<v8::String>, v8::Handle<v8::Value>)’:
../src/node.cc:1311: error: ‘struct v8::HandleScope’ has no member named ‘Close’
../src/node.cc: In function ‘v8::Handle<v8::Value> node::Chdir(const v8::Arguments&)’:
../src/node.cc:1319: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1327: error: ‘ThrowException’ was not declared in this scope
../src/node.cc: In function ‘v8::Handle<v8::Value> node::Cwd(const v8::Arguments&)’:
../src/node.cc:1339: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1345: error: ‘struct v8::HandleScope’ has no member named ‘Close’
../src/node.cc: In function ‘v8::Handle<v8::Value> node::Umask(const v8::Arguments&)’:
../src/node.cc:1361: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1376: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1385: error: ‘struct v8::HandleScope’ has no member named ‘Close’
../src/node.cc: In function ‘v8::Handle<v8::Value> node::GetUid(const v8::Arguments&)’:
../src/node.cc:1393: error: ‘struct v8::HandleScope’ has no member named ‘Close’
../src/node.cc: In function ‘v8::Handle<v8::Value> node::GetGid(const v8::Arguments&)’:
../src/node.cc:1400: error: ‘struct v8::HandleScope’ has no member named ‘Close’
../src/node.cc: In function ‘v8::Handle<v8::Value> node::SetGid(const v8::Arguments&)’:
../src/node.cc:1409: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1425: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1427: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1433: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1438: error: ‘ThrowException’ was not declared in this scope
../src/node.cc: In function ‘v8::Handle<v8::Value> node::SetUid(const v8::Arguments&)’:
../src/node.cc:1448: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1464: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1466: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1472: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1477: error: ‘ThrowException’ was not declared in this scope
../src/node.cc: In function ‘v8::Handle<v8::Value> node::Uptime(const v8::Arguments&)’:
../src/node.cc:1527: error: ‘struct v8::HandleScope’ has no member named ‘Close’
../src/node.cc: In function ‘v8::Handle<v8::Value> node::MemoryUsage(const v8::Arguments&)’:
../src/node.cc:1539: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1545: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1546: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1547: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1548: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1562: error: ‘struct v8::HandleScope’ has no member named ‘Close’
../src/node.cc: In function ‘v8::Handle<v8::Value> node::Kill(const v8::Arguments&)’:
../src/node.cc:1572: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1579: error: ‘ThrowException’ was not declared in this scope
../src/node.cc: In function ‘v8::Handle<v8::Value> node::DLOpen(const v8::Arguments&)’:
../src/node.cc:1606: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1644: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1653: error: ‘ThrowException’ was not declared in this scope
../src/node.cc: In function ‘v8::Handle<v8::Value> node::Compile(const v8::Arguments&)’:
../src/node.cc:1674: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1703: error: ‘struct v8::HandleScope’ has no member named ‘Close’
../src/node.cc: In function ‘void node::FatalException(v8::TryCatch&)’:
../src/node.cc:1727: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1728: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1729: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1738: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
../src/node.cc:1759: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
../src/node.cc: In function ‘v8::Handle<v8::Value> node::Binding(const v8::Arguments&)’:
../src/node.cc:1838: error: ‘ThrowException’ was not declared in this scope
../src/node.cc:1841: error: ‘struct v8::HandleScope’ has no member named ‘Close’
../src/node.cc: In function ‘v8::Handle<v8::Value> node::ProcessTitleGetter(v8::Local<v8::String>, const v8::AccessorInfo&)’:
../src/node.cc:1850: error: ‘struct v8::HandleScope’ has no member named ‘Close’
../src/node.cc:1850: error: ‘Empty’ is not a member of ‘v8::String’
../src/node.cc: In function ‘v8::Handle<v8::Value> node::EnvGetter(v8::Local<v8::String>, const v8::AccessorInfo&)’:
../src/node.cc:1869: error: ‘struct v8::HandleScope’ has no member named ‘Close’
../src/node.cc: In function ‘v8::Handle<v8::Integer> node::EnvQuery(v8::Local<v8::String>, const v8::AccessorInfo&)’:
../src/node.cc:1905: error: ‘struct v8::HandleScope’ has no member named ‘Close’
../src/node.cc: In function ‘v8::Handle<v8::Array> node::EnvEnumerator(const v8::AccessorInfo&)’:
../src/node.cc:1941: error: ‘struct v8::HandleScope’ has no member named ‘Close’
../src/node.cc: In function ‘v8::Handle<v8::Object> node::SetupProcessObject(int, char**)’:
../src/node.cc:1961: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1964: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1968: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1970: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1971: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1972: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1974: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1988: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:1995: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2005: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2006: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2017: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2029: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2031: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2035: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2042: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2044: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2049: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2050: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2051: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2052: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2053: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2056: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2057: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2059: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2060: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2062: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2063: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2064: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2067: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2068: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2070: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc:2073: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node.cc: In function ‘void node::EmitExit(v8::Handle<v8::Object>)’:
../src/node.cc:2411: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
Waf: Leaving directory `/Users/jhford/software/spidernode/build'
Build failed:  -> task failed (err #1): 
    {task: cxx node.cc -> node_3.o}
make: *** [program] Error 1
</pre>

**Comment by sdwilsh** [comment]
Well, we need `v8::String::New(uint16_t*&, size_t&)`

**Comment by sdwilsh** [comment]
And `static Local<String> NewSymbol(const char* data, int length = -1);` (on `String`)
And `template <class T> Local<T> Close(Handle<T> value);` (on `HandleScope`)
And the global method `Handle<Value> V8EXPORT ThrowException(Handle<Value> exception);`
And `static v8::Local<v8::String> Empty();` (on `String`)
And `V8EXPORT static Local<String> Concat(Handle<String> left, Handle<String>right);` (on `String`)

I think that will clear things up.  Patch coming...

**Comment by zpao** [comment]
`ThrowException` is there now (006b2ccce6c3b30eb773350f081a06627d8de3cf). I thought I'd written `String::Empty` but I guess not (that one should be super easy).

**Comment by sdwilsh** [comment]
Ugh...didn't know @zpao already commented saying it was implemented.  Stupid static web page; this comment is now useless.

**Comment by sdwilsh** [comment]
OK; I just pushed a bunch of stuff that should fix all those errors.  Can you pull and try again?  If it works, close this, if it doesn't, please paste a new log of the output.

**Comment by jhford** [comment]
All of the issues handled, but there are new issues.  I will file a new issue for it.
