### ISSUE TITLE
js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Number]’ is private

### ISSUE THREAD

**Issue by jhford** [zpao/v8monkey#49]
Hitting a new error.  This issue is to track

<pre>js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Number]’ is private</pre>

Filing a separate issue for the other errors

<pre>
[52/74] cxx: src/node.cc -> build/default/src/node_3.o
/usr/bin/g++ -pthread -arch x86_64 -g -O3 -DHAVE_OPENSSL=1 -DHAVE_MONOTONIC_CLOCK=0 -DEV_FORK_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_MULTIPLICITY=0 -DX_STACKSIZE=65536 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DEV_MULTIPLICITY=0 -DHAVE_FDATASYNC=0 -DPLATFORM="darwin" -D__POSIX__=1 -Wno-unused-parameter -D_FORTIFY_SOURCE=2 -DNDEBUG -Idefault/src -I../src -Idefault/deps/libeio -I../deps/libeio -Idefault/deps/http_parser -I../deps/http_parser -Idefault/deps/libev -I../deps/libev -Idefault/deps/c-ares -I../deps/c-ares -Idefault/deps/c-ares/darwin-x64 -I../deps/c-ares/darwin-x64 -I/Users/jhford/node/include/js ../src/node.cc -c -o default/src/node_3.o
In file included from ../src/node.cc:70:
../src/node_string.h:35: error: expected class-name before ‘{’ token
/Users/jhford/node/include/js/v8.h: In function ‘v8::Handle<v8::Value> node::FromConstructorTemplate(v8::Persistent<v8::FunctionTemplate>&, const v8::Arguments&)’:
/Users/jhford/node/include/js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Object]’ is private
../src/node.cc:1081: error: within this context
/Users/jhford/node/include/js/v8.h: In function ‘v8::Local<v8::Value> node::Encode(const void*, size_t, node::encoding)’:
/Users/jhford/node/include/js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::String]’ is private
../src/node.cc:1124: error: within this context
../src/node.cc:1124: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
/Users/jhford/node/include/js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::String]’ is private
../src/node.cc:1135: error: within this context
../src/node.cc:1135: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
/Users/jhford/node/include/js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::String]’ is private
../src/node.cc:1140: error: within this context
../src/node.cc:1140: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
/Users/jhford/node/include/js/v8.h: In function ‘v8::Local<v8::Value> node::ExecuteString(v8::Handle<v8::String>, v8::Handle<v8::Value>)’:
/Users/jhford/node/include/js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Value]’ is private
../src/node.cc:1311: error: within this context
/Users/jhford/node/include/js/v8.h: In function ‘v8::Handle<v8::Value> node::Cwd(const v8::Arguments&)’:
/Users/jhford/node/include/js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::String]’ is private
../src/node.cc:1345: error: within this context
/Users/jhford/node/include/js/v8.h: In function ‘v8::Handle<v8::Value> node::Umask(const v8::Arguments&)’:
/Users/jhford/node/include/js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Integer]’ is private
../src/node.cc:1385: error: within this context
/Users/jhford/node/include/js/v8.h: In function ‘v8::Handle<v8::Value> node::GetUid(const v8::Arguments&)’:
/Users/jhford/node/include/js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Integer]’ is private
../src/node.cc:1393: error: within this context
/Users/jhford/node/include/js/v8.h: In function ‘v8::Handle<v8::Value> node::GetGid(const v8::Arguments&)’:
/Users/jhford/node/include/js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Integer]’ is private
../src/node.cc:1400: error: within this context
/Users/jhford/node/include/js/v8.h: In function ‘v8::Handle<v8::Value> node::Uptime(const v8::Arguments&)’:
/Users/jhford/node/include/js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Number]’ is private
../src/node.cc:1527: error: within this context
/Users/jhford/node/include/js/v8.h: In function ‘v8::Handle<v8::Value> node::MemoryUsage(const v8::Arguments&)’:
/Users/jhford/node/include/js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Object]’ is private
../src/node.cc:1562: error: within this context
/Users/jhford/node/include/js/v8.h: In function ‘v8::Handle<v8::Value> node::Compile(const v8::Arguments&)’:
/Users/jhford/node/include/js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Value]’ is private
../src/node.cc:1703: error: within this context
../src/node.cc: In function ‘void node::FatalException(v8::TryCatch&)’:
../src/node.cc:1738: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
../src/node.cc:1759: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
/Users/jhford/node/include/js/v8.h: In function ‘v8::Handle<v8::Value> node::Binding(const v8::Arguments&)’:
/Users/jhford/node/include/js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Object]’ is private
../src/node.cc:1841: error: within this context
/Users/jhford/node/include/js/v8.h: In function ‘v8::Handle<v8::Value> node::ProcessTitleGetter(v8::Local<v8::String>, const v8::AccessorInfo&)’:
/Users/jhford/node/include/js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::String]’ is private
../src/node.cc:1850: error: within this context
/Users/jhford/node/include/js/v8.h: In function ‘v8::Handle<v8::Value> node::EnvGetter(v8::Local<v8::String>, const v8::AccessorInfo&)’:
/Users/jhford/node/include/js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::String]’ is private
../src/node.cc:1869: error: within this context
/Users/jhford/node/include/js/v8.h: In function ‘v8::Handle<v8::Integer> node::EnvQuery(v8::Local<v8::String>, const v8::AccessorInfo&)’:
/Users/jhford/node/include/js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Integer]’ is private
../src/node.cc:1905: error: within this context
/Users/jhford/node/include/js/v8.h: In function ‘v8::Handle<v8::Array> node::EnvEnumerator(const v8::AccessorInfo&)’:
/Users/jhford/node/include/js/v8.h:142: error: ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Array]’ is private
../src/node.cc:1941: error: within this context
../src/node.cc: In function ‘void node::EmitExit(v8::Handle<v8::Object>)’:
../src/node.cc:2411: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
Waf: Leaving directory `/Users/jhford/software/spidernode/build'
Build failed:  -> task failed (err #1): 
    {task: cxx node.cc -> node_3.o}
make: *** [program] Error 1
</pre>

**Comment by jhford** [comment]
Cool. Down to:

<pre>
[52/74] cxx: src/node.cc -> build/default/src/node_3.o
/usr/bin/g++ -pthread -arch x86_64 -g -O3 -DHAVE_OPENSSL=1 -DHAVE_MONOTONIC_CLOCK=0 -DEV_FORK_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_MULTIPLICITY=0 -DX_STACKSIZE=65536 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DEV_MULTIPLICITY=0 -DHAVE_FDATASYNC=0 -DPLATFORM="darwin" -D__POSIX__=1 -Wno-unused-parameter -D_FORTIFY_SOURCE=2 -DNDEBUG -Idefault/src -I../src -Idefault/deps/libeio -I../deps/libeio -Idefault/deps/http_parser -I../deps/http_parser -Idefault/deps/libev -I../deps/libev -Idefault/deps/c-ares -I../deps/c-ares -Idefault/deps/c-ares/darwin-x64 -I../deps/c-ares/darwin-x64 -I/Users/jhford/node/include/js ../src/node.cc -c -o default/src/node_3.o
In file included from ../src/node.cc:70:
../src/node_string.h:35: error: expected class-name before ‘{’ token
../src/node.cc: In function ‘v8::Local<v8::Value> node::Encode(const void*, size_t, node::encoding)’:
../src/node.cc:1124: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
../src/node.cc:1135: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
../src/node.cc:1140: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
../src/node.cc: In function ‘void node::FatalException(v8::TryCatch&)’:
../src/node.cc:1738: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
../src/node.cc:1759: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
../src/node.cc: In function ‘void node::EmitExit(v8::Handle<v8::Object>)’:
../src/node.cc:2411: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
Waf: Leaving directory `/Users/jhford/software/spidernode/build'
Build failed:  -> task failed (err #1): 
    {task: cxx node.cc -> node_3.o}
make: *** [program] Error 1
</pre>

**Comment by sdwilsh** [comment]
And that is tracked in #51 (although I'm not sure what's up with the `../src/node_string.h:35: error: expected class-name before ‘{’ token` and I hope it is just related to the other errors.
