### ISSUE TITLE
Implement Value::Equals

### ISSUE THREAD

**Issue by sdwilsh** [zpao/v8monkey#5]
I'm not really sure how to implement it, so I've asked a question on InfoMonkey.  Once we get an answer, someone should answer it:
http://infomonkey.cdleary.com/questions/209/whats-the-best-way-to-compare-to-jsvals

**Comment by sdwilsh** [comment]
That was fast.  Answer here: http://infomonkey.cdleary.com/questions/209/whats-the-best-way-to-compare-to-jsvals?page=1#211

**Comment by sdwilsh** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=642274 about the new API.  We have to roll our own comparison.

**Comment by sdwilsh** [comment]
Sadly, https://github.com/doublec/mozilla-central/commit/733f538571ccc6ff9586a788b47b70253b09607e did not contain the fix for bug 642274 (it got backed out due to test failures), so we can't fix this yet...

**Comment by sdwilsh** [comment]
This landed in tracemonkey again.

**Comment by sdwilsh** [comment]
This just got merged to mozilla-central and will likely show up on the git mirror in the next few hours.  If we merge, we can resolve this.

**Comment by zpao** [comment]
Implement Value::Equals now that we have JS_LooselyEqual. Closed by a0bc9de89e1d25d6248d102632c589fec3a6bbc6
