### ISSUE TITLE
node.cc:1738: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested

### ISSUE THREAD

**Issue by jhford** [zpao/v8monkey#51]
Hitting a new error.  This issue is to track

<pre>node.cc:1738: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested</pre>

The relevant line of code is:

<pre>Local<Value> argv[1] = { uncaught_exception_symbol_l  };</pre>

<pre>
[52/74] cxx: src/node.cc -> build/default/src/node_3.o
/usr/bin/g++ -pthread -arch x86_64 -g -O3 -DHAVE_OPENSSL=1 -DHAVE_MONOTONIC_CLOCK=0 -DEV_FORK_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_MULTIPLICITY=0 -DX_STACKSIZE=65536 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DEV_MULTIPLICITY=0 -DHAVE_FDATASYNC=0 -DPLATFORM="darwin" -D__POSIX__=1 -Wno-unused-parameter -D_FORTIFY_SOURCE=2 -DNDEBUG -Idefault/src -I../src -Idefault/deps/libeio -I../deps/libeio -Idefault/deps/http_parser -I../deps/http_parser -Idefault/deps/libev -I../deps/libev -Idefault/deps/c-ares -I../deps/c-ares -Idefault/deps/c-ares/darwin-x64 -I../deps/c-ares/darwin-x64 -I/Users/jhford/node/include/js ../src/node.cc -c -o default/src/node_3.o
In file included from ../src/node.cc:70:
../src/node_string.h:35: error: expected class-name before ‘{’ token
../src/node.cc: In function ‘v8::Local<v8::Value> node::Encode(const void*, size_t, node::encoding)’:
../src/node.cc:1124: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
../src/node.cc:1135: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
../src/node.cc:1140: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
../src/node.cc: In function ‘void node::FatalException(v8::TryCatch&)’:
../src/node.cc:1738: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
../src/node.cc:1759: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
../src/node.cc: In function ‘void node::EmitExit(v8::Handle<v8::Object>)’:
../src/node.cc:2411: error: conversion from ‘v8::Local<v8::String>’ to non-scalar type ‘v8::Local<v8::Value>’ requested
Waf: Leaving directory `/Users/jhford/software/spidernode/build'
Build failed:  -> task failed (err #1): 
    {task: cxx node.cc -> node_3.o}
make: *** [program] Error 1
</pre>

edit: removed output related to #48 and #49

**Comment by sdwilsh** [comment]
hmm, I thought @zpao filed an issue about this very recently...

**Comment by jhford** [comment]
i didn't do a check of existing issues, sorry!

**Comment by sdwilsh** [comment]
I don't see it though, so it's possible he just mentioned it on irc...

**Comment by sdwilsh** [comment]
I wonder if @robarnold knows how they have just `Local argv[1]`...

**Comment by zpao** [comment]
Could have been issue #42 which @robarnold just closed. Try again?

**Comment by robarnold** [comment]
Yeah, that looks like issue #42.

**Comment by jhford** [comment]
Different error.

Note to self: do spidernode automation soon!

<pre>
[52/74] cxx: src/node.cc -> build/default/src/node_3.o
/usr/bin/g++ -pthread -arch x86_64 -g -O3 -DHAVE_OPENSSL=1 -DHAVE_MONOTONIC_CLOCK=0 -DEV_FORK_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_MULTIPLICITY=0 -DX_STACKSIZE=65536 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DEV_MULTIPLICITY=0 -DHAVE_FDATASYNC=0 -DPLATFORM="darwin" -D__POSIX__=1 -Wno-unused-parameter -D_FORTIFY_SOURCE=2 -DNDEBUG -Idefault/src -I../src -Idefault/deps/libeio -I../deps/libeio -Idefault/deps/http_parser -I../deps/http_parser -Idefault/deps/libev -I../deps/libev -Idefault/deps/c-ares -I../deps/c-ares -Idefault/deps/c-ares/darwin-x64 -I../deps/c-ares/darwin-x64 -I/Users/jhford/node/include/js ../src/node.cc -c -o default/src/node_3.o
In file included from ../src/node.cc:70:
../src/node_string.h:35: error: expected class-name before ‘{’ token
/Users/jhford/node/include/js/v8.h: In member function ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Object]’:
../src/node.cc:1081:   instantiated from here
/Users/jhford/node/include/js/v8.h:150: error: conversion from ‘long int’ to non-scalar type ‘v8::Local<v8::Object>’ requested
/Users/jhford/node/include/js/v8.h: In member function ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::String]’:
../src/node.cc:1124:   instantiated from here
/Users/jhford/node/include/js/v8.h:150: error: conversion from ‘long int’ to non-scalar type ‘v8::Local<v8::String>’ requested
/Users/jhford/node/include/js/v8.h: In member function ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Value]’:
../src/node.cc:1311:   instantiated from here
/Users/jhford/node/include/js/v8.h:150: error: conversion from ‘long int’ to non-scalar type ‘v8::Local<v8::Value>’ requested
/Users/jhford/node/include/js/v8.h: In member function ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Integer]’:
../src/node.cc:1385:   instantiated from here
/Users/jhford/node/include/js/v8.h:150: error: conversion from ‘long int’ to non-scalar type ‘v8::Local<v8::Integer>’ requested
/Users/jhford/node/include/js/v8.h: In member function ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Number]’:
../src/node.cc:1527:   instantiated from here
/Users/jhford/node/include/js/v8.h:150: error: conversion from ‘long int’ to non-scalar type ‘v8::Local<v8::Number>’ requested
/Users/jhford/node/include/js/v8.h: In member function ‘v8::Local<T> v8::HandleScope::Close(v8::Handle<T>) [with T = v8::Array]’:
../src/node.cc:1941:   instantiated from here
/Users/jhford/node/include/js/v8.h:150: error: conversion from ‘long int’ to non-scalar type ‘v8::Local<v8::Array>’ requested
Waf: Leaving directory `/Users/jhford/software/spidernode/build'
Build failed:  -> task failed (err #1): 
    {task: cxx node.cc -> node_3.o}
make: *** [program] Error 1
</pre>

**Comment by zpao** [comment]
`HandleScope::Close` was implemented in 6296e0849e175c24393c71e61676948489060823 (and node.cc compiles) so we should be good. In the future let's try to keep one error per issue.
