### ISSUE TITLE
error: incomplete type ‘v8::Signature’ used in nested name specifier

### ISSUE THREAD

**Issue by jhford** [zpao/v8monkey#53]
Woo!  node.cc compiles!

<pre>[53/74] cxx: src/node_buffer.cc -> build/default/src/node_buffer_3.o
/usr/bin/g++ -pthread -arch x86_64 -g -O3 -DHAVE_OPENSSL=1 -DHAVE_MONOTONIC_CLOCK=0 -DEV_FORK_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_MULTIPLICITY=0 -DX_STACKSIZE=65536 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DEV_MULTIPLICITY=0 -DHAVE_FDATASYNC=0 -DPLATFORM="darwin" -D__POSIX__=1 -Wno-unused-parameter -D_FORTIFY_SOURCE=2 -DNDEBUG -Idefault/src -I../src -Idefault/deps/libeio -I../deps/libeio -Idefault/deps/http_parser -I../deps/http_parser -Idefault/deps/libev -I../deps/libev -Idefault/deps/c-ares -I../deps/c-ares -Idefault/deps/c-ares/darwin-x64 -I../deps/c-ares/darwin-x64 -I/Users/jhford/node/include/js ../src/node_buffer.cc -c -o default/src/node_buffer_3.o
../src/node_buffer.cc: In static member function ‘static void node::Buffer::Initialize(v8::Handle<v8::Object>)’:
../src/node_buffer.cc:720: error: incomplete type ‘v8::Signature’ used in nested name specifier
../src/node_buffer.cc:721: error: incomplete type ‘v8::Signature’ used in nested name specifier
../src/node_buffer.cc:722: error: incomplete type ‘v8::Signature’ used in nested name specifier
../src/node_buffer.cc:723: error: incomplete type ‘v8::Signature’ used in nested name specifier
../src/node_buffer.cc:726: error: incomplete type ‘v8::Signature’ used in nested name specifier
../src/node_buffer.cc:728: error: incomplete type ‘v8::Signature’ used in nested name specifier
../src/node_buffer.cc:729: error: incomplete type ‘v8::Signature’ used in nested name specifier
../src/node_buffer.cc:730: error: incomplete type ‘v8::Signature’ used in nested name specifier
../src/node_buffer.cc:731: error: incomplete type ‘v8::Signature’ used in nested name specifier
../src/node_buffer.cc:732: error: incomplete type ‘v8::Signature’ used in nested name specifier
../src/node_buffer.cc:733: error: incomplete type ‘v8::Signature’ used in nested name specifier
/Users/jhford/node/include/js/v8.h: In constructor ‘v8::Handle<T>::Handle(v8::Handle<S>) [with S = v8::FunctionTemplate, T = v8::Value]’:
../src/node_buffer.cc:720:   instantiated from here
/Users/jhford/node/include/js/v8.h:178: error: cannot convert ‘v8::FunctionTemplate*’ to ‘v8::Value* volatile’ in assignment
Waf: Leaving directory `/Users/jhford/software/spidernode/build'
Build failed:  -> task failed (err #1): 
    {task: cxx node_buffer.cc -> node_buffer_3.o}
make: *** [program] Error 1
</pre>

**Comment by sdwilsh** [comment]
The two important errors here are:
    error: incomplete type ‘v8::Signature’ used in nested name specifier
    error: cannot convert ‘v8::FunctionTemplate_’ to ‘v8::Value_ volatile’ in assignment

**Comment by zpao** [comment]
I split the second error into it's own issue: #54
