### ISSUE TITLE
Fix test_api.cpp's test_InternalFields failures

### ISSUE THREAD

**Issue by zpao** [zpao/v8monkey#56]
Currently segfaults

```
Calling an unimplemented API: v8::Local<v8::ObjectTemplate> v8::FunctionTemplate::InstanceTemplate()
```

**Comment by sdwilsh** [comment]
This breaks because we don't have `PrivateData` stashed away because @robarnold made `FunctionTemplate` not create new `Function` objects with a `JSClass` that says it has private data.  `ObjectTemplate::SetInternalFieldCount` tries to get this data, and then we assert in the JS engine.
