### ISSUE TITLE
Implement FunctionTemplate::SetClassName

### ISSUE THREAD

**Issue by zpao** [zpao/v8monkey#63]
This one is probably pretty important, but is dependent on changes to SpiderMonkey: https://bugzilla.mozilla.org/show_bug.cgi?id=644166

**Comment by sdwilsh** [comment]
We won't need the upstream stuff anymore.  We can live without it.

**Comment by zpao** [comment]
When this gets fixed, should we file a followup to use something upstream if that ever happens?

**Comment by sdwilsh** [comment]
No, I think our new approach is the right way to go anyway.
