### ISSUE TITLE
Test failure in test_GetterHolders

### ISSUE THREAD

**Issue by sdwilsh** [zpao/v8monkey#72]
Looks like our getters don't work on the prototype chain.  I thought @robarnold had fixed that, but maybe not?

```
TEST-UNEXPECTED-FAIL | c:/Code/v8monkey/js/src/v8api/test/test_api.cpp | Expected '40', got '0' at line 2131
```

**Comment by robarnold** [comment]
This test fails because it sets the prototype on an object created with ObjectTemplate. This has the same cause as issue 65.

**Comment by sdwilsh** [comment]
When I tried to set the accessor stuff on the `Object` created by `ObjectTemplate`, we had a bunch of test failures, fwiw.
