### ISSUE TITLE
standard format for unimplemented tests

### ISSUE THREAD

**Issue by jhford** [zpao/v8monkey#8]
When parsing through the logs, it is useful to find how many tests are unimplemented (TODO).  It is easier to count the number of TODO tests if there is an obvious, universal string for each test that is unimplemented

**Comment by sdwilsh** [comment]
Fixed in 1b7badf3c9e154fad3bfa58bae2b3f4af91d5f69

The message format looks like this:
TEST-INFO | (c:/Code/v8monkey/js/src/v8api/test/test_api.cpp) | TODO test_HulIgennem is DISABLED.  Tracked in https://github.com/zpao/v8monkey/issues/12
