### ISSUE TITLE
Implement the rest of Value::ToInteger

### ISSUE THREAD

**Issue by zpao** [zpao/v8monkey#80]
Issue 45 covered the basic case, but we also need to handle when `JSVAL_IS_INT` is false.

There are issues with our other ToX and XValue implementations as well, so this bug might get morphed to fix all of them.

**Comment by sdwilsh** [comment]
Pretty sure @philikon is working on this!

**Comment by philikon** [comment]
Yes I am

**Comment by philikon** [comment]
My code is over at https://github.com/philikon/v8monkey/commits/. I'm not handling JSVAL_IS_INT yet, but it can't hurt to have people look over it.

**Comment by philikon** [comment]
Two small follow-ups that should allow us to close this issue finally:
- https://github.com/philikon/v8monkey/commit/8d8429e3e7f723be75de0faf1b1aa0a931914839
- https://github.com/philikon/v8monkey/commit/fc6bc3328d703244ffa43570f3a64b3386c10494
  See pull request #96
