### ISSUE TITLE
FunctionTemplate related test failures

### ISSUE THREAD

**Issue by zpao** [zpao/v8monkey#88]
A number of tests that are enabled on master are failing on the template-rewrite branch. So far I'm blaming most of the failures on FunctionTemplate being broken.

CHECK_EQ failures: `test_ObjectTemplate`, `test_FunctionPrototype`, `test_Vector`
Failing `do_check_false(exceptionHandler.HasCaught())`: `test_GlobalObjectTemplate`, `test_Arguments`

**Comment by sdwilsh** [comment]
These are now fixed on branch :)

I'll merge to master in a bit and close the branch.
