### ISSUE TITLE
Move FunctionTemplate::IsFunctionTemplate and ObjectTemplate::IsObjectTemplate to v8::internal

### ISSUE THREAD

**Issue by sdwilsh** [zpao/v8monkey#90]
We should move `FunctionTemplate::IsFunctionTemplate` and `ObjectTemplate::IsObjectTemplate` to `v8::internal` as static methods.  Their implementation will likely want to live in `functiontemplate.cpp` and `objecttemplate.cpp` respectively.

**Comment by nikhilm** [comment]
I'm working on this

**Comment by nikhilm** [comment]
thsi issue should be closed as fixed
